package edunova;

public class Zadatak2 {
//	Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//	By starting with 1 and 2, the first 10 terms will be:
//
//		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//		By considering the terms in the Fibonacci sequence whose 
//		values do not exceed four million, find the sum of the even-valued terms.

public static void main(String[] args) {
	int i,sum=0,fi = 0,prv,drug;
	
	prv=1;
	drug=2;
	
	for(i=0;fi<500000000;i++) {
		fi=prv+drug;
		prv=drug;
		drug=fi;
		if(fi>=500000000) {
			break;
		}
		if(fi%2==0) {
			sum+=fi;
		}
		
		
	}
	sum+=2;
	System.out.println(sum);
}

}

